#!/bin/bash

docker-compose -f docker-compose-connect.yml up -d --force-recreate --build kerio-api

echo "Waiting for services to start"
sleep 20

docker-compose -f docker-compose-connect.yml exec kerio-api ruby -I /work/lib /work/tests/connect-test-inner.rb

docker-compose -f docker-compose-connect.yml down
