#!/usr/bin/env ruby

require 'rspec'
require 'socket'
require 'pp'

def test_port ip, port
  begin
    TCPSocket.new(ip, port)
  rescue Errno::ECONNREFUSED
    return false
  end
  return true
end

file = ARGV.shift
$api = ARGV.shift

RSpec.configure do |config|
  config.color = true
  config.formatter = :documentation
end

exit RSpec::Core::Runner.run([file])
