#!/bin/bash

docker-compose up -d --force-recreate --build kerio-api

echo "Waiting for services to start"
sleep 20

docker-compose exec kerio-api ruby -I /work/lib tests/rspec_run /work/tests/operator_spec.rb https://operator:4021/admin/api/jsonrpc
docker-compose exec kerio-api ruby -I /work/lib tests/rspec_run /work/tests/connect_spec.rb https://connect:4040/admin/api/jsonrpc
docker-compose exec kerio-api ruby -I /work/lib tests/rspec_run /work/tests/control_spec.rb https://172.27.2.16:4081/admin/api/jsonrpc

docker-compose down
rm -rf ./operator-var
